=head1 bigmike specifics

=head3 `users` table

One row for every user

=over

=item id

Primary key; this is how a user is addressed, referenced, and indexed on the
site.

=item username

Display name, and how the user logs in to the site. Pretty much a one-to-one
mapping with id

=item password

SHA512-CRYPT+HASH formatted password. Can be generated using
generate_passwd.php or using the *nix mkpasswd utility by the following:
> mkpasswd -m sha512 USER_PASSWORD
SHA512-CRYPT+HASH passwords are always stored like
$6$(USER_SALT)$(sha512hash(USER_PASSWORD+USER_SALT))
and USER_PASSWORD is never stored plain-text

=item signup_date

=item last_login

=item locked

Describes the user account as being locked. A value of 'y' will forbid this
user from logging in.

=item failed_logins

How many times someone has unsuccessfully attempted to log in to this
account.

=item pref_css

User's preferred style. includes/core.php defines a mascot and CSS
stylesheet for each valid pref_css value

=item invited_by

If the user registered using an invite code, this column describes who
invited him/her. If the user is newer than 3 months, the user that extended
the invitation is considered responsible for this user's behavior.

=back

=head3 `invites` table

One row for every invite that is generated

=over

=item hash

SHA512 (no salt) key

=item ownerid

id of the user in L<`users`|"`users` table">

=item date_created

=back